### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by dcecile** [dcecile/intertwine#1]
### Tasks
- [x] [pnpm](https://pnpm.js.org/)
- [x] [Prettier](https://github.com/dcecile/tinyworkerbee/blob/master/package.json#L67-L72)
- [x] ~[Snowpack](https://www.snowpack.dev/)~
  - [x] ~Hot reload~
  - [x] ~Build~
- [x] [Styles](https://github.com/dcecile/tinyworkerbee/blob/master/effect/index.ts#L106-L195)
- [x] [TypeScript](https://github.com/dcecile/tinyworkerbee/blob/master/tsconfig.json)
  - [x] `checkJs` for Snowpack config
  - [x] `--incremental` with `--noEmit`
  - [x] Skip `baseUrl` config
- [x] VS Code
  - [x] Background task
  - [x] Editor settings
  - [x] Recommended extensions
- [x] [Widgets](https://codepen.io/dcecile/pen/abmQxKw?editors=0010)
  - [x] Get types to pass
  - [x] Add `widgetConfig`
  - [x] Integrate with styles
  - [x] Refine styles
- [x] [ESLint](https://github.com/dcecile/tinyworkerbee/blob/master/package.json#L73-L115)
  - [x] Enable most rules
  - [x] Enable `"import/no-duplicates": "error"`
- [x] [Node HTTP server](https://nodejs.org/api/http.html#http_class_http_server)
- [x] [esbuild](https://esbuild.github.io/)
  - [x] Live reload (client)
  - [x] Live reload (server)
  - [x] Build
- [x] [Tests](https://github.com/dcecile/tinyworkerbee/blob/master/test/index.ts) ([example](https://github.com/dcecile/tinyworkerbee/blob/master/client/developmentMain.ts#L4-L6) [use](https://github.com/dcecile/tinyworkerbee/blob/master/common/message.test.ts) and [packages](https://github.com/dcecile/tinyworkerbee/blob/master/package.json#L36-L37))
  - [x] Basic in-browser tests
  - [x] DOM in-browser tests
  - [x] Threaded context variable
  - [x] Undo `.t` naming
  - [x] Core & server Node.js tests (script & dev)
  - [x] [jsdom](https://github.com/jsdom/jsdom) tests
- [x] Use `NODE_ENV=production/development`
- [x] [dotenv](https://github.com/motdotla/dotenv)
- [x] [GitHub Actions](https://docs.github.com/en/actions)
  - [x] Check
  - [x] Test
  - [x] Build
  - [x] Deploy
- [x] [Fly.io](https://fly.io/)
- [x] [pg](https://github.com/brianc/node-postgres)
  - [x] Only allow specific types for query parameters
  - [x] Set up pool with global error handler
  - [x] Use prepared statements
  - [x] Use [retries](https://github.com/channable/opnieuw/blob/master/opnieuw/retries.py#L153) ([alternative](https://www.npmjs.com/package/cockatiel#exponentialbackoff)) for queries, acquire, and connect
  - [x] Cancel hung queries
  - [x] Return detailed uniqueness errors
  - [x] Hash request ID and upsert
  - [x] Validate request & response & form schema
  - [x] Write tests at all levels (mock DB, time, random, delay)
  - [x] Copy to history on update
- [x] [Dbmate](https://github.com/amacneil/dbmate)
  - [x] First migrations
  - [x] Grant api permissions
  - [x] Deploy migrations
- [x] CockroachDB
  - [x] Local single node
  - [x] [Prettier](https://prettier.io/docs/en/plugins.html#developing-plugins)
  - [x] [CockroachCloud](https://www.cockroachlabs.com/product/cockroachcloud/)
- [x] Rust
  - [x] Use a rustup [toolchain file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) for [1.51.x](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1510-2021-03-25)
  - [x] Add GitHub Action [toolchain](https://github.com/actions-rs/toolchain) (or [workaround](https://github.com/actions-rs/toolchain/issues/126#issuecomment-782989659)) with [caching](https://github.com/actions-rs/toolchain/issues/54#issuecomment-822421472)
  - [x] Set up [rustfmt](https://rust-lang.github.io/rustfmt/) config & CI
  - [x] Set up VS Code language server
  - [x] Set up clippy including including [semicolon rule](https://rust-lang.github.io/rust-clippy/rust-1.52.0/index.html#semicolon_if_nothing_returned)
  - [x] Set up tests
  - [x] Fix app paths
  - [x] Deploy to Fly.io
- [x] [Tantivy](https://github.com/tantivy-search/tantivy)
  - [x] Hello world
  - [x] Create topic
  - [x] Update topic
  - [x] Delete topic
  - [x] Query topics
- [x] [tokio-postgres](https://crates.io/crates/tokio-postgres)
  - [x] Hello world
  - [x] ~Set up [pool](https://docs.rs/bb8-postgres/0.7.0/bb8_postgres/)~
  - [x] Add ~sharded~ update time index to topic table  
  - [x] ~Use [prepared statements](https://docs.rs/tokio-postgres/0.7.5/tokio_postgres/struct.Client.html#method.prepare_typed)~
  - [x] Query topic table for updates (on startup & POST & random delay)
- [x] [hyper](https://hyper.rs/)
  - [x] Basic auth using shared secret
  - [x] Error handling
  - [x] Query Tantivy index from Node.js app
- [x] [node-redis](https://github.com/redis/node-redis)
- [x] [Fly.io Redis](https://fly.io/docs/reference/redis/)
- [ ] [Backblaze](https://www.backblaze.com/b2/cloud-storage.html)
  - [ ] Local fake
- [ ] [MailerSend](https://www.mailersend.com/pricing)
  - [ ] Local fake (open data HTML in browser)
- [ ] [HSTS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security)
  - [ ] Node HTTP
  - [ ] Hyper
- [ ] [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP)

**Comment by dcecile** [comment]
Scoped too large
