### ISSUE TITLE
Extend style module

### ISSUE THREAD

**Issue by dcecile** [dcecile/intertwine#2]
### Tasks
- [ ] Insert rules in inheritance-DAG order
- [ ] Only render `StyleProps` once, add extra selectors to the initial rule
- [ ] Add media query support
- [ ] Add supports query support

**Comment by dcecile** [comment]
Backlog
