### ISSUE TITLE
Authenticated sessions

### ISSUE THREAD

**Issue by dcecile** [dcecile/intertwine#4]
### Tasks

- [ ] Update session info from activity
  - [ ] Batch in groups of 64, send immediately if batch full
  - [ ] If batch not full, throttle to 60 seconds
  - [ ] Send on throttle leading & trailing edge
  - [ ] Use [GeoJS](https://www.geojs.io/docs/v1/endpoints/country/) for country lookups on send (no caching)

**Comment by dcecile** [comment]
Backlog
